export const books = [
  { id: 1, title: '1984', author: 'George Orwell', category: 'Fiction', description: 'A dystopian novel...', rating: 3, img: 'https://m.media-amazon.com/images/I/71rpa1-kyvL._AC_UF1000,1000_QL80_.jpg' },
  { id: 2, title: 'Sapiens', author: 'Yuval Noah Harari', category: 'Non-Fiction', description: 'A brief history of humankind...', rating: 4.5, img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRF2K_1FEDEoFsXb77SZv7b5TsjxKZwCF3NGQ&s' },
  { id: 3, title: 'To Kill a Mockingbird', author: 'Harper Lee', category: 'Fiction', description: 'To Kill a Mockingbird is a novel by the American author Harper Lee...', rating: 2, img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR819TtvIV0JJ5_Wzzfcnk3y2eXfPpamZmdbrg5ofv0Ydafpw_f' },
  { id: 4, title: 'Educated', author: 'Tara Westover', category: 'Biography', description: 'A memoir about growing up in a strict and abusive household in rural Idaho but eventually escaping to learn about the wider world through education.', rating: 4.7, img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9ueGUd997SQG1k-CgzLG0HGNEfxxKtQZFcQ&s' },
  { id: 5, title: 'Dune', author: 'Frank Herbert', category: 'Science Fiction', description: 'A science fiction novel set in a distant future amidst a huge interstellar empire, where noble families vie for control of planets.', rating: 5, img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQD3W7sNidiZiEmcK5XoxY_2ChpNROwqTHr-Q&s' },
  { id: 6, title: 'The Wealth Money Can\'t Buy', author: 'Robin Sharma', category: 'Non-Fiction', description: 'A counterintuitive approach to living a good life.', rating: 3.8, img: 'https://m.media-amazon.com/images/I/71QKQ9mwV7L._AC_UF1000,1000_QL80_.jpg' },
  { id: 7, title: 'Brave New World', author: 'Aldous Huxley', category: 'Fiction', description: 'A futuristic novel about a dystopian society where humans are genetically engineered and controlled.', rating: 4, img: 'https://cdn.kobo.com/book-images/6f07a0e9-8ca8-4b28-982c-7898ac591744/1200/1200/False/brave-new-world-79.jpg' },
  { id: 8, title: 'The Immortal Life of Henrietta Lacks', author: 'Rebecca Skloot', category: 'Biography', description: 'The true story of Henrietta Lacks, whose cancer cells were taken without her knowledge and used in scientific research.', rating: 4.2, img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5CF4S6s9g3XcNPFm5Bz9qjmqxmBwMZiNlxQ&s' },
  { id: 9, title: 'The Martian', author: 'Andy Weir', category: 'Science Fiction', description: 'A novel about an astronaut stranded on Mars and his survival efforts.', rating: 4.9, img: 'https://m.media-amazon.com/images/I/51QimqeXMXL._AC_UF1000,1000_QL80_.jpg' },
  { id: 10, title: 'APJ abdul kalam wings of fire', author: ' Arun Tiwari', category: 'Biography', description: 'Wings of Fire, is the autobiography of the Missile Man of India and the former President of India, Dr. A. P. J. Abdul Kalam. It was written by him and Arun Tiwari', rating: 4.8, img: 'https://img.etimg.com/photo/msid-99141634,imgsize-63020/WINGSOFFIRE-AUTOBIOGRAPHYOFABDULKALAM.jpg' },
  { id: 11, title: 'Foundation', author: 'Isaac Asimov', category: 'Science Fiction', description: 'A classic sci-fi series about the rise and fall of galactic civilizations.', rating: 4.7, img: 'https://m.media-amazon.com/images/I/71Eib8TOVpL._AC_UF1000,1000_QL80_.jpg' },
  { id: 12, title: 'Atomic Habits', author: 'James Clear', category: 'Non-Fiction', description: 'An easy & proven way to build good habits & break bad ones.', rating: 4.5, img: 'https://m.media-amazon.com/images/I/61M6KzUbf7L._AC_UF350,350_QL80_.jpg' },
  { id: 13, title: 'Pride and Prejudice', author: 'Jane Austen', category: 'Fiction', description: 'A classic novel about love and society in the 19th century England.', rating: 5, img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcaMiDUNdKNStBh0coU2WSyf4infRYKNXRhA&s' },
  { id: 14, title: 'Steve Jobs', author: 'Walter Isaacson', category: 'Biography', description: 'A biography of the Apple co-founder Steve Jobs.', rating: 4.5, img: 'https://cdn.kobo.com/book-images/caee148f-5805-45bd-9cbf-938f2373b8d8/353/569/90/False/steve-jobs-the-life-lessons-rules-for-success.jpg' },
  { id: 15, title: 'Neuromancer', author: 'William Gibson', category: 'Science Fiction', description: 'A novel that popularized the cyberpunk genre, set in a dystopian future.', rating: 4.4, img: 'https://m.media-amazon.com/images/I/81m-rJnUdRL._AC_UF1000,1000_QL80_.jpg' },
  { id: 16, title: 'Fahrenheit 451', author: 'Ray Bradbury', category: 'Fiction', description: 'A dystopian novel about a future where books are banned and "firemen" burn any that are found.', rating: 3.9, img: 'https://m.media-amazon.com/images/I/61l8LHt4MeL._AC_UF1000,1000_QL80_.jpg' },
  { id: 17, title: 'The Power of Habit', author: 'Charles Duhigg', category: 'Non-Fiction', description: 'A book about why we do what we do in life and business, based on behavioral science.', rating: 4.3, img: 'https://m.media-amazon.com/images/I/71ONWR6eXDL._AC_UF1000,1000_QL80_.jpg' },
  { id: 18, title: 'The Right Stuff', author: 'Tom Wolfe', category: 'Biography', description: 'The story of the test pilots who were selected to be the first astronauts.', rating: 4.6, img: 'https://m.media-amazon.com/images/I/61NlRzW2ZmL._AC_UF1000,1000_QL80_.jpg' },
  { id: 19, title: 'Snow Crash', author: 'Neal Stephenson', category: 'Science Fiction', description: 'A fast-paced cyberpunk novel set in a futuristic America.', rating: 4.5, img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPSXFY8Cp0E0yzHQ34vE0TFAgHvHwIQq_ILw&s' },
  {
    id: 20, title: 'Crime and Punishment', author: 'Fyodor Dostoevsky', category: 'Fiction', description: 'A psychological novel about a young man who commits a murder and the moral dilemmas that follow.', rating: 4.8, img: 'https://m.media-amazon.com/images/I/71O2XIytdqL._AC_UF1000,1000_QL80_.jpg'
  }
]